Repository 100-hours-a-week/18-team-timeline-be, pull requests merged in 2025-05, with the labels that each got.

#18 feat: 에러 핸들러 생성, JWT 예외 처리 설정 추가, global 패키지 구조 리팩토링
  backend/.DS_Store
  backend/src/.DS_Store
  backend/src/main/.DS_Store
  backend/src/main/java/.DS_Store
  backend/src/main/java/com/.DS_Store
  backend/src/main/java/com/tamnara/.DS_Store
  backend/src/main/java/com/tamnara/backend/.DS_Store
  backend/src/main/java/com/tamnara/backend/global/config/JpaConfig.java
  backend/src/main/java/com/tamnara/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/tamnara/backend/global/config/SwaggerConfig.java
  backend/src/main/java/com/tamnara/backend/global/config/WebConfig.java
  backend/src/main/java/com/tamnara/backend/global/exception/CustomException.java
  backend/src/main/java/com/tamnara/backend/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/tamnara/backend/global/response/ErrorResponse.java
  backend/src/main/java/com/tamnara/backend/global/security/JwtAccessDeniedHandler.java
  backend/src/main/java/com/tamnara/backend/global/security/JwtAuthenticationHandler.java
  backend/src/main/java/com/tamnara/backend/user/.DS_Store
  backend/src/main/resources/application.properties
Labels: feat

#19 feat: 뉴스 서비스 및 컨트롤러 구현, 일부 API 테스트 완료
  backend/.DS_Store
  backend/src/.DS_Store
  backend/src/main/.DS_Store
  backend/src/main/java/.DS_Store
  backend/src/main/java/com/.DS_Store
  backend/src/main/java/com/tamnara/.DS_Store
  backend/src/main/java/com/tamnara/backend/.DS_Store
  backend/src/main/java/com/tamnara/backend/bookmark/domain/Bookmark.java
  backend/src/main/java/com/tamnara/backend/bookmark/repository/BookmarkRepository.java
  backend/src/main/java/com/tamnara/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/tamnara/backend/global/config/WebClientConfig.java
  backend/src/main/java/com/tamnara/backend/global/exception/CustomException.java
  backend/src/main/java/com/tamnara/backend/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/tamnara/backend/global/jwt/JwtProvider.java
  backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
  backend/src/main/java/com/tamnara/backend/news/domain/News.java
  backend/src/main/java/com/tamnara/backend/news/domain/TimelineCard.java
  backend/src/main/java/com/tamnara/backend/news/dto/NewsCardDTO.java
  backend/src/main/java/com/tamnara/backend/news/dto/StatisticsDTO.java
  backend/src/main/java/com/tamnara/backend/news/dto/TimelineCardDTO.java
  backend/src/main/java/com/tamnara/backend/news/dto/request/AINewsRequest.java
  backend/src/main/java/com/tamnara/backend/news/dto/request/AIStatisticsRequest.java
  backend/src/main/java/com/tamnara/backend/news/dto/request/AITimelineMergeReqeust.java
  backend/src/main/java/com/tamnara/backend/news/dto/request/NewsCreateRequest.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/AINewsResponse.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/NewsDetailResponse.java
  backend/src/main/java/com/tamnara/backend/news/repository/CategoryRepository.java
  backend/src/main/java/com/tamnara/backend/news/repository/NewsTagRepository.java
  backend/src/main/java/com/tamnara/backend/news/repository/TagRepository.java
  backend/src/main/java/com/tamnara/backend/news/repository/TimelineCardRepository.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsService.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
  backend/src/main/java/com/tamnara/backend/news/util/ValueOfEnum.java
  backend/src/main/java/com/tamnara/backend/news/util/ValueOfEnumValidator.java
  backend/src/main/java/com/tamnara/backend/user/controller/UserController.java
  backend/src/main/java/com/tamnara/backend/user/dto/UserInfoDto.java
  backend/src/main/java/com/tamnara/backend/user/dto/UserUpdateRequestDto.java
  backend/src/test/java/com/tamnara/backend/bookmark/RepositoryTest/BookmarkRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/comment/RepositoryTest/CommentRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/news/RepositoryTest/CategoryRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/news/RepositoryTest/TagRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/news/RepositoryTest/TimelineCardRepositoryTest.java
Labels: feat

#24 chore: SecurityConfig에 CORS 설정 및 JWT 인증 필터 등록
  backend/src/main/java/com/tamnara/backend/global/config/SecurityConfig.java
Labels: chore, feat

#29 Revert "update: 핫이슈 뉴스 응답 구조 수정 및 이미지 필드 네이밍 통일, 중복 이미지 대응"
  backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
  backend/src/main/java/com/tamnara/backend/news/repository/NewsImageRepository.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
Labels: feat

#36 fix: 뉴스 생성/업데이트 API 연동 테스트 완료
  backend/build.gradle
  backend/src/main/java/com/tamnara/backend/global/config/WebClientConfig.java
  backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
  backend/src/main/java/com/tamnara/backend/news/dto/NewsCardDTO.java
  backend/src/main/java/com/tamnara/backend/news/dto/TimelineCardDTO.java
  backend/src/main/java/com/tamnara/backend/news/dto/WrappedDTO.java
  backend/src/main/java/com/tamnara/backend/news/dto/request/AINewsRequest.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/AINewsResponse.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/NewsDetailResponse.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
Labels: fix

#40 fix: DB 설정 및 AI URL 환경변수화, 문자열 길이 제한 완화 및 이미지 필드 처리 수정
  backend/src/main/java/com/tamnara/backend/global/config/WebClientConfig.java
  backend/src/main/java/com/tamnara/backend/news/domain/News.java
  backend/src/main/java/com/tamnara/backend/news/domain/TimelineCard.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/AINewsResponse.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/NewsDetailResponse.java
  backend/src/main/java/com/tamnara/backend/news/repository/NewsImageRepository.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/tamnara/backend/news/RepositoryTest/NewsImageRepositoryTest.java
Labels: refactor, fix

#42 refactor: FE 및 BE URL, EC2 Public URL 환경변수화, 타임라인 카드 저장 로직 수정
  backend/src/main/java/com/tamnara/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/tamnara/backend/global/config/SwaggerConfig.java
  backend/src/main/java/com/tamnara/backend/global/config/WebClientConfig.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
  backend/src/main/resources/application.properties
Labels: refactor

#54 [풀스택] [fix] AI에 타임라인 병합 요청 시, 실패하거나 응답이 부적절하게 나오는 문제 해결
  backend/src/main/java/com/tamnara/backend/news/dto/request/AITimelineMergeRequest.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
Labels: refactor, fix

#58 fix: '전체' 카테고리의 뉴스 카드 추가 로딩 로직 추가
  backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsService.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
Labels: normal bug, fix

#93 [풀스택] [fix] 뉴스 관련 로직 및 예외 처리 개선 및 타임라인 병합 조건 수정
  backend/src/main/java/com/tamnara/backend/global/exception/AIException.java
  backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
  backend/src/main/java/com/tamnara/backend/news/repository/NewsImageRepository.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsService.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
Labels: refactor, fix

#94 [풀스택] [refactor] 댓글 삭제 응답 및 서비스 로직 정리
  backend/src/main/java/com/tamnara/backend/comment/controller/CommentController.java
  backend/src/main/java/com/tamnara/backend/comment/service/CommentService.java
  backend/src/main/java/com/tamnara/backend/comment/service/CommentServiceImpl.java
Labels: refactor

#95 [풀스택] [refactor] 북마크 해제 응답 및 서비스 로직 정리
  backend/src/main/java/com/tamnara/backend/bookmark/controller/BookmarkController.java
  backend/src/main/java/com/tamnara/backend/bookmark/service/BookmarkService.java
  backend/src/main/java/com/tamnara/backend/bookmark/service/BookmarkServiceImpl.java
Labels: refactor

#124 refactor(user): Map 및 기존 DTO 제거, 명시적 응답 타입 적용
  backend/src/main/java/com/tamnara/backend/user/controller/UserController.java
  backend/src/main/java/com/tamnara/backend/user/dto/EmailAvailabilityResponse.java
  backend/src/main/java/com/tamnara/backend/user/dto/NicknameAvailabilityResponse.java
  backend/src/main/java/com/tamnara/backend/user/dto/SignupRequest.java
  backend/src/main/java/com/tamnara/backend/user/dto/SignupResponse.java
  backend/src/main/java/com/tamnara/backend/user/dto/UserEmailCheckResponseDto.java
  backend/src/main/java/com/tamnara/backend/user/dto/UserInfo.java
  backend/src/main/java/com/tamnara/backend/user/dto/UserInfoResponseDto.java
  backend/src/main/java/com/tamnara/backend/user/dto/UserUpdateResponse.java
  backend/src/main/java/com/tamnara/backend/user/service/UserService.java
  backend/src/test/java/com/tamnara/backend/user/service/UserServiceTest.java
Labels: refactor

#125 refactor(auth): 카카오 로그인 응답에 명시적 DTO 적용
  backend/src/main/java/com/tamnara/backend/auth/controller/KakaoController.java
  backend/src/main/java/com/tamnara/backend/auth/dto/KakaoLoginResponseDto.java
  backend/src/main/java/com/tamnara/backend/auth/dto/KakaoLoginUrlResponse.java
  backend/src/main/java/com/tamnara/backend/auth/dto/KakaoUrlResponseDto.java
  backend/src/main/java/com/tamnara/backend/auth/service/KakaoService.java
Labels: refactor

#126 refactor(user): 테스트 코드에 명시적 DTO 적용
  backend/src/main/java/com/tamnara/backend/user/dto/UserUpdateRequest.java
  backend/src/test/java/com/tamnara/backend/user/controller/UserControllerIntegrationTest.java
  backend/src/test/java/com/tamnara/backend/user/service/UserServiceTest.java
Labels: refactor

#130 [풀스택] [refactor] WrappedDTO의 패키지 경로 변경 및 SecurityConfig에서 CORS 설정 및 필터 체인 설정 추가
  backend/src/main/java/com/tamnara/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/tamnara/backend/global/exception/AIException.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
Labels: chore

#96 [풀스택] [refactor] 뉴스 생성/업데이트 로직에서 여론 통계 생성 API 요청을 비동기 처리
  backend/src/main/java/com/tamnara/backend/BackendApplication.java
  backend/src/main/java/com/tamnara/backend/global/exception/AIException.java
  backend/src/main/java/com/tamnara/backend/news/service/AsyncAIService.java
  backend/src/main/java/com/tamnara/backend/news/service/AsyncAIServiceImpl.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
Labels: feat, refactor

#134 [풀스택] [feat] 뉴스 응답 포맷 개선(feature/news-api-response) 내용 feature/news에 병합
  backend/src/main/java/com/tamnara/backend/global/config/JpaConfig.java
  backend/src/main/java/com/tamnara/backend/global/config/SwaggerConfig.java
  backend/src/main/java/com/tamnara/backend/global/config/WebClientConfig.java
  backend/src/main/java/com/tamnara/backend/global/dto/WrappedDTO.java
  backend/src/main/java/com/tamnara/backend/global/exception/AIException.java
  backend/src/main/java/com/tamnara/backend/global/exception/CustomException.java
  backend/src/main/java/com/tamnara/backend/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
  backend/src/main/java/com/tamnara/backend/news/dto/NewsDetailDTO.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/HotissueNewsListResponse.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/NewsDetailResponse.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/NewsListResponse.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/category/AllResponse.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/category/EconomyResponse.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/category/EntertainmentResponse.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/category/KtbResponse.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/category/MultiCategoryResponse.java
  backend/src/main/java/com/tamnara/backend/news/dto/response/category/SportsResponse.java
  backend/src/main/java/com/tamnara/backend/news/service/AsyncAIService.java
  backend/src/main/java/com/tamnara/backend/news/service/AsyncAIServiceImpl.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsService.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
  backend/src/main/java/com/tamnara/backend/news/util/ValueOfEnum.java
  backend/src/main/java/com/tamnara/backend/news/util/ValueOfEnumValidator.java
Labels: feat, refactor

#164 refactor: 회원 기능 응답 메시지 상수화 및 하드코딩 제거
  backend/src/main/java/com/tamnara/backend/user/constant/UserResponseMessage.java
  backend/src/main/java/com/tamnara/backend/user/controller/UserController.java
  backend/src/main/java/com/tamnara/backend/user/service/UserService.java
Labels: refactor

#191 refactor: 회원 기능 예외 처리 및 메시지 통합 개선
  backend/src/main/java/com/tamnara/backend/user/constant/UserResponseMessage.java
  backend/src/main/java/com/tamnara/backend/user/controller/UserController.java
  backend/src/main/java/com/tamnara/backend/user/exception/DuplicateEmailException.java
  backend/src/main/java/com/tamnara/backend/user/exception/DuplicateUsernameException.java
  backend/src/main/java/com/tamnara/backend/user/exception/InactiveUserException.java
  backend/src/main/java/com/tamnara/backend/user/exception/UserNotFoundException.java
  backend/src/main/java/com/tamnara/backend/user/service/UserService.java
  backend/src/test/java/com/tamnara/backend/user/controller/UserControllerIntegrationTest.java
  backend/src/test/java/com/tamnara/backend/user/service/UserServiceTest.java
Labels: refactor
