Repository 100-hours-a-week/18-team-timeline-be, pull requests merged in 2025-06, with the labels that each got.

#227 feat: 뉴스 생성 서비스 로직 보완
  backend/src/main/java/com/tamnara/backend/news/repository/NewsTagRepository.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
  backend/src/test/java/com/tamnara/backend/news/repository/NewsTagRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/news/service/NewsServiceImplTest.java
Labels: feat

#239 refactor: 입력 키워드 목록과 태그 목록이 일치하는 뉴스 조회 메서드의 경로 변경
  backend/src/main/java/com/tamnara/backend/news/repository/NewsRepository.java
  backend/src/main/java/com/tamnara/backend/news/repository/NewsTagRepository.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
  backend/src/test/java/com/tamnara/backend/news/repository/NewsRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/news/repository/NewsTagRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/news/service/NewsServiceImplTest.java
Labels: refactor

#242 refactor: 인증/인가 예외 처리 분리 및 응답 메시지 개선
  backend/src/main/java/com/tamnara/backend/global/constant/ResponseMessage.java
  backend/src/main/java/com/tamnara/backend/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/tamnara/backend/global/exception/SecurityExceptionHandler.java
Labels: refactor

#247 chore: QueryDSL 의존성 및 설정 추가
  .DS_Store
  .gitignore
  backend/build.gradle
  backend/src/main/java/com/tamnara/backend/global/config/QuerydslConfig.java
Labels: chore

#254 chore: 스케줄링 기능 활성화를 위한 설정 클래스 추가
  backend/src/main/java/com/tamnara/backend/global/config/SchedulingConfig.java
Labels: chore

#255 feat: 투표 통계 자동 집계 기능 추가
  backend/src/main/java/com/tamnara/backend/poll/domain/VoteStatistics.java
  backend/src/main/java/com/tamnara/backend/poll/repository/VoteRepository.java
  backend/src/main/java/com/tamnara/backend/poll/repository/VoteStatisticsRepository.java
  backend/src/main/java/com/tamnara/backend/poll/scheduler/VoteStatisticsScheduler.java
  backend/src/main/java/com/tamnara/backend/poll/service/PollService.java
  backend/src/main/java/com/tamnara/backend/poll/service/VoteStatisticsService.java
  backend/src/main/java/com/tamnara/backend/poll/util/PollBuilder.java
  backend/src/main/java/com/tamnara/backend/poll/util/VoteStatisticsBuilder.java
Labels: feat

#261 feat: 투표 통계 조회 API 구현
  backend/src/main/java/com/tamnara/backend/poll/controller/PollController.java
  backend/src/main/java/com/tamnara/backend/poll/domain/VoteStatistics.java
  backend/src/main/java/com/tamnara/backend/poll/dto/OptionResult.java
  backend/src/main/java/com/tamnara/backend/poll/dto/PollStatisticsResponse.java
  backend/src/main/java/com/tamnara/backend/poll/service/VoteStatisticsService.java
Labels: feat

#263 fix: 뉴스 상세 조회 시 뉴스의 수정일자가 현재 시점으로 변경되는 버그 해결
  backend/src/main/java/com/tamnara/backend/news/repository/NewsRepository.java
  backend/src/main/java/com/tamnara/backend/news/service/AIServiceImpl.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
  backend/src/test/java/com/tamnara/backend/news/repository/NewsRepositoryTest.java
Labels: fix

#264 chore: 테스트 유틸리티 클래스 위치 이동 및 네이밍 정리
  backend/src/test/java/com/tamnara/backend/auth/service/KakaoServiceTest.java
  backend/src/test/java/com/tamnara/backend/global/util/CreateUserUtil.java
  backend/src/test/java/com/tamnara/backend/global/util/TestUtil.java
Labels: refactor

#267 test: Poll 도메인 관련 Repository 단위 테스트 추가
  backend/src/main/java/com/tamnara/backend/poll/domain/VoteStatistics.java
  backend/src/main/java/com/tamnara/backend/poll/repository/PollOptionRepository.java
  backend/src/main/java/com/tamnara/backend/poll/repository/PollRepository.java
  backend/src/test/java/com/tamnara/backend/poll/domain/PollTest.java
  backend/src/test/java/com/tamnara/backend/poll/repository/PollOptionRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/poll/repository/PollRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/poll/repository/VoteRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/poll/repository/VoteStatisticsRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/poll/util/PollOptionTestBuilder.java
  backend/src/test/java/com/tamnara/backend/poll/util/PollTestBuilder.java
  backend/src/test/java/com/tamnara/backend/poll/util/VoteTestBuilder.java
  backend/src/test/java/com/tamnara/backend/user/repository/UserRepositoryTest.java
Labels: test

#278 feat: 알림 기능 API 구현
  backend/src/main/java/com/tamnara/backend/alarm/constant/AlarmResponseMessage.java
  backend/src/main/java/com/tamnara/backend/alarm/constant/AlarmServiceConstant.java
  backend/src/main/java/com/tamnara/backend/alarm/controller/AlarmController.java
  backend/src/main/java/com/tamnara/backend/alarm/domain/Alarm.java
  backend/src/main/java/com/tamnara/backend/alarm/domain/AlarmType.java
  backend/src/main/java/com/tamnara/backend/alarm/domain/UserAlarm.java
  backend/src/main/java/com/tamnara/backend/alarm/dto/AlarmCardDTO.java
  backend/src/main/java/com/tamnara/backend/alarm/dto/response/AlarmListResponse.java
  backend/src/main/java/com/tamnara/backend/alarm/repository/AlarmRepository.java
  backend/src/main/java/com/tamnara/backend/alarm/repository/UserAlarmRepository.java
  backend/src/main/java/com/tamnara/backend/alarm/service/AlarmSchedulerService.java
  backend/src/main/java/com/tamnara/backend/alarm/service/AlarmSchedulerServiceImpl.java
  backend/src/main/java/com/tamnara/backend/alarm/service/AlarmService.java
  backend/src/main/java/com/tamnara/backend/alarm/service/AlarmServiceImpl.java
  backend/src/main/java/com/tamnara/backend/global/security/CustomAuthenticationEntryPoint.java
  backend/src/test/java/com/tamnara/backend/alarm/config/AlarmServiceMockConfig.java
  backend/src/test/java/com/tamnara/backend/alarm/controller/AlarmControllerTest.java
  backend/src/test/java/com/tamnara/backend/alarm/domain/AlarmTest.java
  backend/src/test/java/com/tamnara/backend/alarm/domain/UserAlarmTest.java
  backend/src/test/java/com/tamnara/backend/alarm/repository/AlarmRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/alarm/repository/UserAlarmRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/alarm/service/AlarmSchedulerServiceImplTest.java
  backend/src/test/java/com/tamnara/backend/alarm/service/AlarmServiceImplTest.java
Labels: feat

#297 feat: 단위 테스트 추가 for PollService, VoteService, and VoteStatisticsService
  backend/src/main/java/com/tamnara/backend/poll/dto/PollCreateRequest.java
  backend/src/main/java/com/tamnara/backend/poll/dto/PollOptionCreateRequest.java
  backend/src/main/java/com/tamnara/backend/poll/service/PollService.java
  backend/src/test/java/com/tamnara/backend/poll/service/PollServiceTest.java
  backend/src/test/java/com/tamnara/backend/poll/service/VoteServiceTest.java
  backend/src/test/java/com/tamnara/backend/poll/service/VoteStatisticsServiceTest.java
  backend/src/test/java/com/tamnara/backend/poll/util/PollCreateRequestTestBuilder.java
  backend/src/test/java/com/tamnara/backend/poll/util/PollTestBuilder.java
Labels: test

#298 feat: Scheduler 관련 유닛 테스트 추가
  backend/src/test/java/com/tamnara/backend/poll/scheduler/PollStateSchedulerTest.java
  backend/src/test/java/com/tamnara/backend/poll/scheduler/VoteStatisticsSchedulerTest.java
Labels: test

#303 feat: JpaConfig와 QuerydslConfig를 추가한 테스트용 설정 클래스 추가
  backend/src/test/java/com/tamnara/backend/config/TestConfig.java
Labels: chore, test

#304 refactor: 리포지토리 테스트의 @import 목록을 TestConfig로 변경
  backend/src/test/java/com/tamnara/backend/alarm/repository/AlarmRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/alarm/repository/UserAlarmRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/bookmark/repository/BookmarkRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/comment/repository/CommentRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/news/repository/CategoryRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/news/repository/NewsImageRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/news/repository/NewsRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/news/repository/NewsTagRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/news/repository/TagRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/news/repository/TimelineCardRepositoryTest.java
Labels: fix, test

#300 feat: PollController 통합 테스트 구현
  backend/src/test/java/com/tamnara/backend/global/util/CreateUserUtil.java
  backend/src/test/java/com/tamnara/backend/poll/controller/PollControllerIntegrationTest.java
Labels: test

#365 feat: KTB 뉴스 수동 생성 API 추가 및 뉴스 공개 전환 자동화 스케줄링 서비스 추가
  backend/src/main/java/com/tamnara/backend/global/constant/ResponseMessage.java
  backend/src/main/java/com/tamnara/backend/news/controller/NewsController.java
  backend/src/main/java/com/tamnara/backend/news/domain/News.java
  backend/src/main/java/com/tamnara/backend/news/dto/request/KtbNewsCreateRequest.java
  backend/src/main/java/com/tamnara/backend/news/repository/NewsRepository.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsSchedulerService.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsSchedulerServiceImpl.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsService.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
  backend/src/main/java/com/tamnara/backend/poll/controller/PollController.java
  backend/src/main/java/com/tamnara/backend/user/controller/UserController.java
  backend/src/main/java/com/tamnara/backend/user/exception/InactiveUserException.java
  backend/src/test/java/com/tamnara/backend/news/controller/NewsControllerTest.java
  backend/src/test/java/com/tamnara/backend/news/domain/NewsTest.java
  backend/src/test/java/com/tamnara/backend/news/repository/NewsRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/news/service/NewsSchedulerServiceImplTest.java
  backend/src/test/java/com/tamnara/backend/news/service/NewsServiceImplTest.java
  backend/src/test/java/com/tamnara/backend/user/controller/UserControllerIntegrationTest.java
Labels: feat

#309 feat: 뉴스 서비스 알림 이벤트 발행 추가
  backend/src/main/java/com/tamnara/backend/news/repository/NewsRepository.java
  backend/src/main/java/com/tamnara/backend/news/service/NewsServiceImpl.java
  backend/src/test/java/com/tamnara/backend/alarm/integration/AlarmIntegrationTest.java
  backend/src/test/java/com/tamnara/backend/config/SyncAsyncConfig.java
  backend/src/test/java/com/tamnara/backend/news/service/NewsServiceImplTest.java
  backend/src/test/resources/application-test.properties
Labels: feat

#310 feat: 투표 서비스에 알림 이벤트 발행자 추가
  backend/src/main/java/com/tamnara/backend/poll/service/PollService.java
  backend/src/test/java/com/tamnara/backend/poll/service/PollServiceTest.java
Labels: feat

#391 fix: 누락된 어노테이션 추가
  backend/src/main/java/com/tamnara/backend/poll/service/PollSchedulerServiceImpl.java
  backend/src/main/java/com/tamnara/backend/poll/service/PollServiceImpl.java
  backend/src/main/java/com/tamnara/backend/poll/service/VoteServiceImpl.java
Labels: fix

#390 release: v2.2.1 투표 도메인 엔티티의 연관관계에 `on Delete` 삭제 정책 추가 및 서비스 기능 로직 변경
  backend/src/main/java/com/tamnara/backend/poll/domain/Poll.java
  backend/src/main/java/com/tamnara/backend/poll/domain/PollOption.java
  backend/src/main/java/com/tamnara/backend/poll/domain/Vote.java
  backend/src/main/java/com/tamnara/backend/poll/domain/VoteStatistics.java
  backend/src/main/java/com/tamnara/backend/poll/repository/PollRepository.java
  backend/src/main/java/com/tamnara/backend/poll/scheduler/PollStateScheduler.java
  backend/src/main/java/com/tamnara/backend/poll/scheduler/VoteStatisticsScheduler.java
  backend/src/main/java/com/tamnara/backend/poll/service/PollSchedulerService.java
  backend/src/main/java/com/tamnara/backend/poll/service/PollSchedulerServiceImpl.java
  backend/src/main/java/com/tamnara/backend/poll/service/PollService.java
  backend/src/main/java/com/tamnara/backend/poll/service/PollServiceImpl.java
  backend/src/main/java/com/tamnara/backend/poll/service/VoteServiceImpl.java
  backend/src/main/java/com/tamnara/backend/poll/service/VoteStatisticsService.java
  backend/src/main/java/com/tamnara/backend/poll/service/VoteStatisticsServiceImpl.java
  backend/src/test/java/com/tamnara/backend/poll/config/PollTestConfig.java
  backend/src/test/java/com/tamnara/backend/poll/repository/PollRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/poll/scheduler/PollStateSchedulerTest.java
  backend/src/test/java/com/tamnara/backend/poll/scheduler/VoteStatisticsSchedulerTest.java
  backend/src/test/java/com/tamnara/backend/poll/service/PollSchedulerServiceTest.java
  backend/src/test/java/com/tamnara/backend/poll/service/PollServiceImplTest.java
  backend/src/test/java/com/tamnara/backend/poll/service/VoteServiceImplTest.java
  backend/src/test/java/com/tamnara/backend/poll/service/VoteStatisticsServiceTest.java
Labels: refactor, release

#401 fix: 댓글 목록 조회 리포지토리 메서드명을 최신순 정렬 방식에 맞게 변경
  backend/src/main/java/com/tamnara/backend/comment/repository/CommentRepository.java
  backend/src/main/java/com/tamnara/backend/comment/service/CommentServiceImpl.java
  backend/src/test/java/com/tamnara/backend/comment/repository/CommentRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/comment/service/CommentServiceImplTest.java
Labels: fix

#406 feat: JWT 토큰을 HttpOnly Secure Cookie에 저장, refresh token 추가 및 Redis 연동하여 저장
  backend/src/main/java/com/tamnara/backend/auth/client/KakaoApiClientImpl.java
  backend/src/main/java/com/tamnara/backend/auth/constant/AuthResponseMessage.java
  backend/src/main/java/com/tamnara/backend/auth/controller/AuthController.java
  backend/src/main/java/com/tamnara/backend/auth/controller/KakaoController.java
  backend/src/main/java/com/tamnara/backend/auth/dto/CheckAuthResponse.java
  backend/src/main/java/com/tamnara/backend/auth/service/AuthService.java
  backend/src/main/java/com/tamnara/backend/auth/service/AuthServiceImpl.java
  backend/src/main/java/com/tamnara/backend/auth/service/KakaoService.java
  backend/src/main/java/com/tamnara/backend/auth/service/KakaoServiceImpl.java
  backend/src/main/java/com/tamnara/backend/global/config/RedisConfig.java
  backend/src/main/java/com/tamnara/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/tamnara/backend/global/constant/JwtConstant.java
  backend/src/main/java/com/tamnara/backend/global/jwt/JwtProvider.java
  backend/src/main/java/com/tamnara/backend/global/security/JwtAuthenticationFilter.java
  backend/src/main/java/com/tamnara/backend/user/controller/UserController.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/tamnara/backend/auth/config/AuthServiceMockConfig.java
  backend/src/test/java/com/tamnara/backend/auth/config/KakaoApiClientMockConfig.java
  backend/src/test/java/com/tamnara/backend/auth/controller/AuthControllerIntegrationTest.java
  backend/src/test/java/com/tamnara/backend/auth/controller/KakaoControllerIntegrationTest.java
  backend/src/test/java/com/tamnara/backend/auth/service/AuthServiceImplTest.java
  backend/src/test/java/com/tamnara/backend/auth/service/KakaoServiceImplTest.java
  backend/src/test/java/com/tamnara/backend/auth/service/KakaoServiceTest.java
  backend/src/test/resources/application-test.properties
Labels: chore, feat

#412 feat: 카카오 OAuth 링크 상수화 및 Users 도메인의 일부 필드 중복 허용, 닉네임 중복 여부 확인 API 제거
  backend/src/main/java/com/tamnara/backend/auth/client/KakaoApiClientImpl.java
  backend/src/main/java/com/tamnara/backend/auth/constant/KakaoOAuthConstant.java
  backend/src/main/java/com/tamnara/backend/auth/service/KakaoServiceImpl.java
  backend/src/main/java/com/tamnara/backend/user/controller/UserController.java
  backend/src/main/java/com/tamnara/backend/user/domain/User.java
  backend/src/main/java/com/tamnara/backend/user/repository/UserRepository.java
  backend/src/main/java/com/tamnara/backend/user/service/UserService.java
  backend/src/main/java/com/tamnara/backend/user/service/UserServiceImpl.java
  backend/src/test/java/com/tamnara/backend/auth/controller/KakaoControllerIntegrationTest.java
  backend/src/test/java/com/tamnara/backend/user/controller/UserControllerIntegrationTest.java
  backend/src/test/java/com/tamnara/backend/user/repository/UserRepositoryTest.java
  backend/src/test/java/com/tamnara/backend/user/service/UserServiceTest.java
Labels: refactor
